apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: why-kubernetes
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes
    repoURL: https://github.com/jkleinlercher/suxess-why-why-why.git
    targetRevision: main